banking-system/accounts/urls.py
from django.conf.urls import url
from .views import (
    login_view,
    register_view,
    logout_view
)


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

banking-system/bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, generate_pdf


urlpatterns = [
    # admin
    url(r'^super_secret/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^GeneratePdf/$', generate_pdf, name='generate_pdf'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
    #transfers
    url(r'^', include('transfer.urls', namespace='transfer')),
    #adminMask
    url(r'^',include('adminMask.urls',namespace='adminMask')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

banking-system/transactions/urls.py
from django.conf.urls import url

from .views import deposit_view, withdrawal_view

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', deposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    
]

banking-system/transfer/urls.py
from django.conf.urls import url
from .views import transfer_fund
from .views import foreign_fund

urlpatterns = [
    url(r'^transfer/$', transfer_fund, name='fund_transfer'),
    url(r'^ftransfer/$', foreign_fund, name='foreign_fund'),
]

banking-system/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.IntegerField(unique=True, blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None


class AccountDetail(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    picture = models.ImageField(
        null=True,
        blank=True,
        upload_to='account_pictures/',
    )

    def __str__(self):
        return str(self.account_no)


class UserAddresse(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email

banking-system/core/models.py
from django.db import models

# Create your models here.

banking-system/core/views.py
import os

from django.db.models import Sum
from django.shortcuts import render
from transactions.models import Deposit, Withdrawal, Interest
from transfer.models import transfer
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


import pdfkit


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        deposit = Deposit.objects.filter(user=user)
        transfer1 = transfer.objects.filter(sender=user)
        transfer2 = transfer.objects.filter(receiver=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']
        

        context = {
                    "user": user,
                    "transfer1":transfer1,
                    "transfer2":transfer2,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})


@login_required()
def generate_pdf(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        transfer1 = transfer.objects.filter(sender=user)
        transfer2 = transfer.objects.filter(receiver=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        data = {
            "user": user,
            "transfer1": transfer1,
            "transfer2": transfer2,
            "deposit": deposit,
            "deposit_sum": deposit_sum,
            "withdrawal": withdrawal,
            "withdrawal_sum": withdrawal_sum,
            "interest": interest,
            "interest_sum": interest_sum,
        }
    path = os.getcwd()
    template = get_template(path + "/core/templates/core/transactions.html")
    context = data  # data is the context data that is sent to the html file to render the output.
    html = template.render(context)  # Renders the template with the context data.
    pdfkit.from_string(html, 'out.pdf')
    pdf = open("out.pdf")
    response = HttpResponse(pdf.read(), content_type='application/pdf')  # Generates the response as pdf response.
    response['Content-Disposition'] = 'attachment; filename=output.pdf'
    pdf.close()
    os.remove("out.pdf")  # remove the locally created pdf file.
    return response  # returns the response.

banking-system/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

<h1>About US</h1>
<hr>
<p>An internet banking portal with features like fund transfer,account balance checking and foreign fund transfer.</p>

<p>This web app is a prototype made using django, as a part of Software Engineering Lab project.
</p>


<p>Team 11: CASA</p>

{% endblock content %}

banking-system/core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} Banking System {% endblock title %}</title>
    <style>
       /* unvisited link */
        a:link {
          color: black;
        }

        /* visited link */
        a:visited {
          color: black;
        }
        /* mouse over link */
        a:hover {
          color: black;
        }

        /* selected link */
        a:active {
            color: black;
        }
        #popup{display:none; background:#efefef; border:2px solid black; margin: 15px; padding: 10px;}
    </style>
    <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body style="background-image: url('../../../static/banking-system/images/pig.jpg'); background-size: cover; font-family: 'DejaVu Sans'">
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
{% block content %}

{% endblock content %}
</div>
{% include "core/footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
  $('#p123').on('keyup', function(){
    $('#ch123').val($(this).val()*73.96);
  })
</script>
  </body>
</html>

banking-system/core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Banking App</b></h4>
                <p>Made by CASA</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2020Copyright: <a href="http://127.0.0.1:8000/"> banking-system.com</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

banking-system/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px; color: #16002c;">
<div class="jumbotron text-center" style="border-color: black; border-width: thick; background-image: url('../../../static/banking-system/images/bank.jpg');">
      <div class="container">
        <h1 class="jumbotron-heading">Banking System</h1>
        <hr>
        <p class="lead text-muted">An internet banking portal made as a part of lab project.</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Login</a>
          <a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Create a Bank Account</a>
        </p>
      </div>
</div>
</div>

{% endblock content %}

banking-system/core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

banking-system/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'home' %}">Banking System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm" type="button">Login</a> |
            <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm" type="button">Create an Account</a>
        {% endif %}
    </form>
  </div>
</nav>

banking-system/core/templates/core/transactions.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
    <div class="page-header">
      <h1 class="text-center"><b>Banking System</b><br><small>ABC Bank Ltd.</small></h1>
    </div>
    
<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>
    <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
    <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
    <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
    <h4><b>Email Address: </b>{{ user.email }}</h4>
    <h4><b>Address: </b>{{ user.full_address }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>{{ user.balance }} /-</h4>
        <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
        <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
        <a class="btn btn-success" href="{% url 'transfer:fund_transfer' %}">Transfer</a>
        <a class="btn btn-success" style="margin-top: 7px" onclick="document.getElementById('popup').style.display='block'">Request Checkbook</a>
            <div id="popup">Checkbook is send to your permanent address!
                <a class="btn btn-success" onclick="document.getElementById('popup').style.display='none'">Hide</a>
            </div>
        </a>
        <a class="btn btn-danger" href="{% url 'transfer:foreign_fund' %}" style="margin-top: 7px">Foreign Funds Transfer</a>
    </div>
  </div>

</div>

<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Transaction Details</b></h2>
</div>

<h3>Deposit Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount /-</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>

<h3>Transfer Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Receiver</th>
      <th>Amount /-</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in transfer1 %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Debit</td>
      <td>{{ obj.receiver.account.account_no}}</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    {% for obj in transfer2 %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Credit</td>
      <td>{{ obj.receiver.account.account_no}}</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Withdrawal Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount /-</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Withdrawal</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ withdrawal_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount /-</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>
    <a class="btn btn-danger" href="{% url 'accounts:register' %}">Update Info</a>
    <a class="btn btn-danger" href="{% url 'generate_pdf' %}" role="button">Generate PDF</a>
<hr>

{% endblock content %}