banking-system/accounts/urls.py
from django.conf.urls import url
from .views import (
    login_view,
    register_view,
    logout_view
)


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

banking-system/adminMask/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^admin/$', views.get_ip, name='admin'),
	url(r'^admin_res/$', views.admin_res, name='admin_res'),
]

banking-system/bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, generate_pdf


urlpatterns = [
    # admin
    url(r'^super_secret/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^GeneratePdf/$', generate_pdf, name='generate_pdf'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
    #transfers
    url(r'^', include('transfer.urls', namespace='transfer')),
    #adminMask
    url(r'^',include('adminMask.urls',namespace='adminMask')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

banking-system/adminMask/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

banking-system/adminMask/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from ipaddr import client_ip

def admin_res(request):
	return render(request,"req_res.html")


def get_ip(request):
    ipaddr = client_ip(request)
    print("Public IP address of intruder is:")
    print(ipaddr)
    return render(request, "fakelogin.html")

banking-system/adminMask/templates/fakelogin.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
<h2>Admin Login</h2><hr>
<form> 
Email ID:<br> 
<input type="text"> 
<br> 
Password:<br> 
<input type="text" name="email_id"> 
<br><br> 
<a class="btn btn-success" href="{% url 'adminMask:admin_res' %}">Transfer</a> 
</form> 
{% endblock content %}

banking-system/adminMask/templates/req_res.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
<h2>This system is secured.</h2><hr>
{% endblock content %}